version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8000:80"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - LLAMA_CLOUD_KEY=${LLAMA_CLOUD_KEY}
    container_name: norm-ai-backend

  frontend:
    working_dir: /app
    image: node:18-alpine
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      - BACKEND_URL=http://backend:80
    command: sh -c "npm install && npm run dev"
    container_name: norm-ai-frontend
    depends_on:
      - backend

networks:
  default:
    name: norm-ai-network